### PR TITLE
Streaming support for conversation history with SSE

### LINKED ISSUE #179: Gemini-cli stdout logs don't appear until the task is canceled or complete
Gemini-cli task logs are not working very well.

Log messages to stderr show up immediately. But logs to stdout don't appear in the task "Logs" section until the task has been canceled or has finished running.

Do other agent logs work better?

This is using vibe-kanban@0.0.46 and gemini 0.1.11 on MacOS 26.0b2

### LINKED ISSUE #180: Gemini tasks never finish
Created Gemini task and let it run but it never completes. It loops the last response over and over, and in my case it kept doing this until I stopped it (notice the size of the veritical scrollbar).

This is happening with `@google/gemini-cli@0.1.12`.

Image

### PR DESCRIPTION
**Pull request by abcpro1**
The main focus was on Gemini-CLI token streaming, which uses the standard JSON-Patch format to stream real-time updates to the frontend via SSE.

There is also a default database-backed SSE implementation which covers the remaining executors like Claude-code.

Should resolve #179.
Hopefully resolves #180.

### CODE REVIEW

**Comment by LSRCT** [comment]
Tried it and after starting a task the streaming works.
When switching between a running gemini task and another one in the UI the gemini conversation sometimes doesn't render and loses the text previously rendered.

File: backend/src/executors/claude.rs
Comment (stunningpixels) [inline backend/src/executors/claude.rs:1]: I think there is a utility for resolving symlinks somewhere

File: backend/src/executors/gemini/streaming.rs [hunk 1]
```diff
@@ -0,0 +1,365 @@
...
+    /// Push patches to the Gemini WAL system
+    pub fn push_patch(execution_process_id: Uuid, patches: Vec<Value>, content_length: usize) {
+        let mut wal_map = GEMINI_WAL_MAP.lock().unwrap();
+        let wal_state = wal_map.entry(execution_process_id).or_default();
+        let config = GeminiStreamConfig::default();
+
+        // Update access time for orphan cleanup
+        wal_state.last_access = Instant::now();
+
+        // Validate patches to prevent null entries and malformed operations
```
Comment (stunningpixels) [inline backend/src/executors/gemini/streaming.rs]: Might be worth trying to figure out the root of these

File: backend/src/routes/task_attempts.rs [hunk 2]
```diff
@@ -47,6 +48,29 @@ pub struct FollowUpResponse {
     pub actual_attempt_id: Uuid,
     pub created_new_attempt: bool,
 }
+/// Extended response for normalized logs that includes WAL for resumable streaming
+#[derive(Debug, Serialize)]
+pub struct NormalizedConversationWithWal {
+    #[serde(flatten)]
+    pub conversation: NormalizedConversation,
```
Comment (stunningpixels) [inline backend/src/routes/task_attempts.rs]: Probably one or the other, not both

File: backend/src/routes/task_attempts.rs [hunk 3]
```diff
@@ -1184,20 +1214,41 @@ pub async fn get_execution_process_normalized_logs(
     let has_stderr =
         process.stderr.is_some() && !process.stderr.as_ref().unwrap().trim().is_empty();
 
-    // If the process is still running and has no stdout/stderr, return empty logs
+    // If the process is still running and has no stdout/stderr, return empty logs with WAL if available
     if process.status == ExecutionProcessStatus::Running && !has_stdout && !has_stderr {
```
Comment (stunningpixels) [inline backend/src/routes/task_attempts.rs]: This is probably unnecessary

File: backend/src/routes/task_attempts.rs [hunk 4]
```diff
@@ -1132,8 +1161,9 @@ pub async fn get_task_attempt_execution_state(
 
 pub async fn get_execution_process_normalized_logs(
```
Comment (stunningpixels) [inline backend/src/routes/task_attempts.rs]: When process is running we probably always call the stream endpoint, when it's not running we call this one so can always get from DB to simplify things

File: frontend/src/components/tasks/TaskDetails/LogsTab/NormalizedConversationViewer.tsx [hunk 5]
```diff
@@ -20,113 +29,248 @@ interface NormalizedConversationViewerProps {
...
+    }
+
+    if (manager.reconnectTimeout) {
+      clearTimeout(manager.reconnectTimeout);
+      manager.reconnectTimeout = null;
+    }
+  }, []);
+
   const fetchNormalizedLogs = useCallback(
     async (isPolling = false) => {
```
Comment (stunningpixels) [inline frontend/src/components/tasks/TaskDetails/LogsTab/NormalizedConversationViewer.tsx]: Remove polling, either the process is running and we use SSE, or not and we get the logs from the existing endpoint once

File: backend/src/routes/task_attempts.rs
Comment (stunningpixels) [inline backend/src/routes/task_attempts.rs:1]: I guess we can 100% revert the changes here to make merge/rebase easier

File: backend/src/routes/stream.rs [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+
+            if is_gemini {
+                // Gemini streaming: Read from Gemini WAL using cursor
+                let cursor = if last_seen_batch_id == 0 { None } else { Some(last_seen_batch_id) };
+                if let Some(new_batches) = GeminiExecutor::get_wal_batches(process_id, cursor) {
+                    // Send any new batches since last cursor
+                    for batch in &new_batches {
+                        // Send full batch including batch_id for cursor tracking
+                        let batch_data = serde_json::json!({
+                            "batch_id": batch.batch_id,
```
Comment (stunningpixels) [inline backend/src/routes/stream.rs]: This can be a struct

File: backend/src/routes/stream.rs [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+
+                                // Use working directory for normalization
+                                let working_dir = &proc.working_directory;
+
+                                // Normalize the full stdout content to get proper conversation structure
+                                if let Ok(normalized) = executor.normalize_logs(&stdout, working_dir) {
+                                    // Use exact entry count tracking instead of flawed ratio calculation
+                                    let new_entries = &normalized.entries[last_entry_count..];
+
+                                    if !new_entries.is_empty() {
```
Comment (stunningpixels) [inline backend/src/routes/stream.rs]: This logic is too nested, please adopt and_then

**Review by stunningpixels — CHANGES_REQUESTED** [review]
