### PR TITLE
Fix WebSocket connection for process logs viewer

### LINKED ISSUE #732: [BUG] Dev Server Script Logs | Process Details -  Connection failed
## Description

When I click on "DEV" inside a ticket to start the server and then check for logs, I get the message:

**"Connection failed."**

Image

### PR DESCRIPTION
**Pull request by alcibiadesc**
## Summary
This PR fixes the 'Connection failed' error that appears when trying to view process logs (e.g., dev server logs).

Fixes #732

## Problem
The backend was migrated from Server-Sent Events (SSE) to WebSocket in a recent commit, but the frontend `useLogStream` hook was still attempting to connect via EventSource. This mismatch caused connection failures when users tried to view logs.

## Solution
Updated the `useLogStream` hook to:
- Use WebSocket connection instead of EventSource
- Connect to the correct endpoint (`/api/execution-processes/{id}/raw-logs/ws`)
- Parse messages using the LogMsg format (JsonPatch, Finished)
- Maintain all existing retry and error handling logic

## Test Plan
1. Start a dev server for any task
2. Click on the logs viewer button
3. Verify that logs are displayed correctly in real-time
4. Confirm no 'Connection failed' errors appear

### CODE REVIEW

**Comment by alcibiadesc** [comment]
issue related #732

File: frontend/src/hooks/useLogStream.ts [hunk 1]
```diff
@@ -41,36 +43,41 @@ export const useLogStream = (processId: string): UseLogStreamResult => {
...
+                case 'STDOUT':
+                case 'STDERR':
+                  addLogEntry({ type: value.type, content: value.content });
+                  break;
+                // Ignore other patch types (NORMALIZED_ENTRY, DIFF, etc.)
+                default:
+                  break;
+              }
+            });
+          } else if ('Finished' in data) {
```
Comment (stunningpixels) [inline frontend/src/hooks/useLogStream.ts]: {"finished":true}

https://github.com/BloopAI/vibe-kanban/blob/main/crates/utils/src/log_msg.rs#L57

**Comment by alcibiadesc** [comment]
> Thanks for flagging this issue - this is a good start and handles the happy case, however on testing failure cases I am getting into a loop with the ws being called repeatedly. Can look into this more tomorrow

Thanks a lot for the project and for looking into this! Really appreciate your work on it.

**Comment by alcibiadesc** [comment]
Hi @stunningpixels ,  

Thanks again for reviewing! I’ve applied your feedback regarding the WebSocket handling. Please take a look when you get a chance and let me know if there’s anything else that needs adjustment.

**Comment by stunningpixels** [comment]
Nice one!
