### PR TITLE
Setup script error output

### LINKED ISSUE #152: Project setup logs are not shown on error
If the project setup fails, the logs are not shown. You get this:

Image

Suggestion: change the UI to still show the logs to enable faster diagnosis.

### PR DESCRIPTION
**Pull request by abcpro1**
fixes #152

### CODE REVIEW

File: frontend/src/utils/logUtils.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+/**
+ * Utility functions for processing execution logs
+ */
+
+/**
+ * Filters out internal stderr boundary markers from raw output
+ * These markers are used internally to separate stderr chunks but should not be visible to users
+ */
+export function filterStderrBoundaryMarkers(text: string): string {
+  return text.replace(/---STDERR_CHUNK_BOUNDARY---\n?/g, '');
```
Comment (stunningpixels) [inline frontend/src/utils/logUtils.ts]: Could we filter these on the backend?

File: backend/src/routes/task_attempts.rs [hunk 2]
```diff
@@ -1215,67 +1217,81 @@ pub async fn get_execution_process_normalized_logs(
...
 
-            let executor = executor_config.create_executor();
+            // Special handling for setup scripts (process_type = 'setupscript' with executor_type = None)
+            if process.process_type == ExecutionProcessType::SetupScript
+                && executor_type == "unknown"
+            {
+                // For setup scripts, create a simple normalized conversation with stdout content
+                stdout_entries = vec![crate::executor::NormalizedEntry {
+                    timestamp: None,
+                    entry_type: crate::executor::NormalizedEntryType::SystemMessage,
```
Comment (stunningpixels) [inline backend/src/routes/task_attempts.rs]: Could we not create this normalised entry in the setup_script normalize_logs fn and then treat setup script like any other executor, rather than a special case?

**Review by stunningpixels — APPROVED** [review]
