### PR TITLE
fix: config migration and CI windows build fixes for opencode

### LINKED ISSUE #250: opencode update broke install
Now getting :

Error: unknown variant opencode, expected one of echo, claude, amp, gemini, setup-script, setup_script, claude-code-router, charm-opencode, charmopencode

How do I clean my install? npx and npn uninstall do not fix this

### PR DESCRIPTION
**Pull request by abcpro1**
fixes #250

### CODE REVIEW

File: backend/src/executor.rs [hunk 1]
```diff
@@ -428,7 +429,14 @@ impl ExecutorConfig {
                 dirs::home_dir().map(|home| home.join(".gemini").join("settings.json"))
             }
             ExecutorConfig::SstOpencode => {
-                xdg::BaseDirectories::with_prefix("opencode").get_config_file("opencode.json")
+                #[cfg(unix)]
+                {
+                    xdg::BaseDirectories::with_prefix("opencode").get_config_file("opencode.json")
```
Comment (ggordonhall) [inline backend/src/executor.rs:434]: Why do we need this library in this case? Why can't we do `dirs::config_dir().join(...)`?

**Review by ggordonhall — APPROVED** [review]

File: backend/src/executor.rs (hunk 1 above)
Comment (abcpro1) [reply backend/src/executor.rs:434]: `sst opencode` uses XDG on macOS. `dirs::config_dir` returns `~/Library/Application Support/...` instead of `~/.config`
