### PR TITLE
sst Opencode

### LINKED ISSUE #169: OpenCode has no `--output-format=json` param.
when launching opencode, vibe-kanban might pass like:
```
opencode -p "project_id: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d\n\nTask title: 实现用户认证功能\nTask description: 添加通过邮箱和密码进行注册和登录的功能。" --output-format=json
```, 
but sst/opencode has no --output-format=json param.

so opencode is not working in vibe-kanban.

since kimi k2 is so good at tool calling, k2 + opencode is really an alternative to claude code.

### PR DESCRIPTION
**Pull request by abcpro1**
resolves #169.

### CODE REVIEW

**Comment by ggaabe** [comment]
good work!

File: backend/src/executors/sst_opencode/tests.rs [hunk 1]
```diff
@@ -0,0 +1,329 @@
+use super::*;
+use crate::{
+    executor::ActionType,
+    executors::sst_opencode::{format_opencode_content_as_normalized_json, SstOpencodeExecutor},
+};
+
+#[test]
```
Comment (ggordonhall) [inline backend/src/executors/sst_opencode/tests.rs]: Let's move these tests inline

**Review by ggordonhall — APPROVED** [review]
